export const hypotheses = [
  "network_degradation",
  "db_connection_pool",
  "db_overload",
  "cpu_saturation",
  "memory_leak",
  "bad_deployment",
  "dns_failure",
  "external_dependency",
  "cache_failure",
];
const commonDeploy = [
  {
    version: "v2.8.0",
    time: "2 days ago",
    status: "HEALTHY",
    changes: ["routine dependency updates"],
  },
];
const base = (
  id,
  title,
  severity,
  service,
  difficulty,
  root,
  symptoms,
  evidence,
  remediation,
  timeline,
) => ({
  id,
  title,
  severity,
  service,
  difficulty,
  rootCause: root,
  symptoms,
  evidence,
  remediation,
  timeline,
});
export const scenarios = [
  base(
    "INC-1042",
    "Orders API Latency Spike",
    "SEV-2",
    "orders-api",
    "MEDIUM",
    "db_connection_pool",
    {
      latency: 2.8,
      p50: 0.9,
      p95: 2.8,
      p99: 4.7,
      errorRate: 8.4,
      rps: 612,
      cpu: 71,
      memory: 64,
    },
    {
      metrics: {
        points: [
          0.21, 0.22, 0.23, 0.24, 0.26, 0.31, 0.44, 0.72, 1.1, 1.8, 2.8, 2.6,
        ],
        note: "p95 latency rose sharply after connection utilization increased.",
      },
      logs: [
        ["14:31:48", "INFO", "orders-api", "Request received"],
        ["14:31:49", "INFO", "orders-api", "DB query started"],
        ["14:31:51", "WARN", "orders-api", "Connection acquisition delayed"],
        ["14:31:53", "WARN", "orders-api", "Pool utilization 100%"],
        ["14:31:55", "ERROR", "orders-api", "Request timeout"],
        [
          "14:31:56",
          "ERROR",
          "orders-api",
          "Failed to acquire database connection",
        ],
        ["14:32:01", "INFO", "orders-api", "Retry scheduled"],
        ["14:32:04", "WARN", "orders-api", "Request queue growing"],
      ],
      network: {
        path: ["Client", "Load Balancer", "orders-api", "PostgreSQL"],
        latency: ["12ms", "8ms", "2.4s"],
        failures: "8.1% request timeouts",
      },
      database: {
        active: 20,
        idle: 0,
        max: 20,
        waiting: 47,
        avg: "1.8s",
        p95: "4.3s",
        locks: 3,
        note: "Connections remain occupied longer than expected.",
      },
      deployment: [
        {
          version: "v2.8.1",
          time: "14:24 UTC",
          status: "DEPLOYED",
          changes: ["connection handling refactor", "retry middleware update"],
        },
        ...commonDeploy,
      ],
    },
    [
      { label: "Rollback v2.8.1", key: "rollback", correct: true },
      {
        label: "Clear leaked connections",
        key: "clear_connections",
        correct: true,
      },
      { label: "Increase CPU", key: "increase_cpu", correct: false },
      { label: "Disable database", key: "disable_db", correct: false },
    ],
    [
      "14:20",
      "Deployment v2.8.1",
      "14:24",
      "Connection usage begins increasing",
      "14:29",
      "Pool reaches 80%",
      "14:31",
      "Pool reaches 100%",
      "14:32",
      "API latency increases",
      "14:33",
      "Error rate increases",
      "14:34",
      "Incident detected",
    ],
  ),
  base(
    "INC-1108",
    "Heap Growth in Catalog API",
    "SEV-2",
    "catalog-api",
    "MEDIUM",
    "memory_leak",
    {
      latency: 1.9,
      p50: 0.6,
      p95: 1.9,
      p99: 3.1,
      errorRate: 3.2,
      rps: 440,
      cpu: 68,
      memory: 94,
    },
    {
      metrics: {
        points: [62, 64, 67, 71, 76, 83, 88, 94],
        note: "Memory rises continuously instead of returning after garbage collection.",
      },
      logs: [
        ["09:10:02", "INFO", "catalog-api", "GC cycle completed"],
        [
          "09:14:12",
          "WARN",
          "catalog-api",
          "Old heap occupancy above baseline",
        ],
        ["09:19:33", "WARN", "catalog-api", "GC frequency increasing"],
        ["09:25:11", "ERROR", "catalog-api", "Allocation pressure detected"],
        [
          "09:26:03",
          "WARN",
          "catalog-api",
          "Container restart threshold approaching",
        ],
        [
          "09:27:15",
          "ERROR",
          "catalog-api",
          "Worker restarted after OOM guard",
        ],
      ],
      network: {
        path: ["Client", "Load Balancer", "catalog-api", "Search API"],
        latency: ["11ms", "7ms", "180ms"],
        failures: "0.9%",
      },
      database: {
        active: 8,
        idle: 12,
        max: 30,
        waiting: 0,
        avg: "42ms",
        p95: "91ms",
        locks: 1,
        note: "Database health is normal.",
      },
      deployment: [
        {
          version: "v4.2.0",
          time: "08:40 UTC",
          status: "DEPLOYED",
          changes: ["catalog cache refactor"],
        },
        ...commonDeploy,
      ],
    },
    [
      { label: "Rollback v4.2.0", key: "rollback", correct: true },
      { label: "Restart service", key: "restart", correct: true },
      { label: "Increase DB pool", key: "increase_pool", correct: false },
      { label: "Flush DNS", key: "dns", correct: false },
    ],
    [
      "08:40",
      "Deployment v4.2.0",
      "09:14",
      "Heap occupancy warning",
      "09:25",
      "GC pressure increases",
      "09:27",
      "Worker restart",
      "09:29",
      "Latency alert",
    ],
  ),
  base(
    "INC-1181",
    "Checkout Error Regression",
    "SEV-1",
    "checkout-api",
    "EASY",
    "bad_deployment",
    {
      latency: 2.2,
      p50: 0.7,
      p95: 2.2,
      p99: 4.1,
      errorRate: 12.4,
      rps: 380,
      cpu: 55,
      memory: 57,
    },
    {
      metrics: {
        points: [0.3, 0.3, 0.31, 0.32, 0.34, 0.4, 0.7, 1.1, 2.2],
        note: "Error rate and latency change immediately after the release.",
      },
      logs: [
        ["16:02:10", "INFO", "checkout-api", "Release v2.8.1 active"],
        [
          "16:03:01",
          "ERROR",
          "checkout-api",
          "Unhandled TypeError in discount calculation",
        ],
        ["16:03:04", "ERROR", "checkout-api", "POST /checkout returned 500"],
        ["16:04:17", "WARN", "checkout-api", "5xx rate above threshold"],
      ],
      network: {
        path: ["Client", "Load Balancer", "checkout-api", "Payment API"],
        latency: ["9ms", "6ms", "190ms"],
        failures: "12.4%",
      },
      database: {
        active: 9,
        idle: 18,
        max: 30,
        waiting: 0,
        avg: "35ms",
        p95: "80ms",
        locks: 0,
        note: "Healthy.",
      },
      deployment: [
        {
          version: "v2.8.1",
          time: "16:02 UTC",
          status: "DEPLOYED",
          changes: ["discount calculation refactor"],
        },
        {
          version: "v2.8.0",
          time: "yesterday",
          status: "HEALTHY",
          changes: ["minor UI changes"],
        },
      ],
    },
    [
      { label: "Rollback v2.8.1", key: "rollback", correct: true },
      { label: "Restart service", key: "restart", correct: true },
      { label: "Increase DB pool", key: "increase_pool", correct: false },
      { label: "Disable load balancer", key: "lb", correct: false },
    ],
    [
      "16:00",
      "Baseline healthy",
      "16:02",
      "v2.8.1 deployed",
      "16:03",
      "Unhandled TypeError appears",
      "16:04",
      "5xx alert fires",
    ],
  ),
  base(
    "INC-1217",
    "Dependency Hostname Resolution Failure",
    "SEV-2",
    "orders-api",
    "EASY",
    "dns_failure",
    {
      latency: 3.8,
      p50: 1.2,
      p95: 3.8,
      p99: 6.1,
      errorRate: 18.1,
      rps: 510,
      cpu: 43,
      memory: 61,
    },
    {
      metrics: {
        points: [0.3, 0.3, 0.31, 0.32, 0.35, 0.4, 0.9, 2.1, 3.8],
        note: "Dependency request failures rise while compute resources remain healthy.",
      },
      logs: [
        [
          "11:42:01",
          "ERROR",
          "orders-api",
          "getaddrinfo ENOTFOUND payments.internal",
        ],
        ["11:42:02", "WARN", "orders-api", "Payment dependency retry"],
        ["11:42:05", "ERROR", "orders-api", "DNS resolution timeout"],
        ["11:42:10", "ERROR", "orders-api", "Checkout request failed"],
      ],
      network: {
        path: ["orders-api", "DNS Resolver", "payments.internal"],
        latency: ["4ms", "timeout", "N/A"],
        failures: "91% DNS failures",
      },
      database: {
        active: 7,
        idle: 14,
        max: 30,
        waiting: 0,
        avg: "38ms",
        p95: "73ms",
        locks: 0,
        note: "Healthy.",
      },
      deployment: [
        {
          version: "v6.1.4",
          time: "yesterday",
          status: "HEALTHY",
          changes: ["logging improvements"],
        },
      ],
    },
    [
      { label: "Flush DNS/cache", key: "dns", correct: true },
      { label: "Rollback deployment", key: "rollback", correct: false },
      { label: "Increase DB pool", key: "increase_pool", correct: false },
      { label: "Increase CPU", key: "increase_cpu", correct: false },
    ],
    [
      "11:40",
      "Healthy baseline",
      "11:42",
      "DNS resolution failures begin",
      "11:43",
      "Retries increase",
      "11:45",
      "Checkout errors alert",
    ],
  ),
  base(
    "INC-1273",
    "Payment Provider Slowness",
    "SEV-2",
    "orders-api",
    "HARD",
    "external_dependency",
    {
      latency: 4.1,
      p50: 1.4,
      p95: 4.1,
      p99: 6.8,
      errorRate: 9.3,
      rps: 590,
      cpu: 58,
      memory: 63,
    },
    {
      metrics: {
        points: [0.3, 0.31, 0.32, 0.33, 0.35, 0.38, 0.6, 1.4, 2.6, 4.1],
        note: "Application latency tracks the external provider latency.",
      },
      logs: [
        ["18:08:01", "INFO", "orders-api", "Payment request started"],
        ["18:08:02", "WARN", "orders-api", "payment-service response 1.8s"],
        ["18:08:04", "WARN", "orders-api", "payment-service response 4.7s"],
        ["18:08:06", "ERROR", "orders-api", "Payment request timeout"],
        ["18:08:07", "INFO", "orders-api", "Retrying payment request"],
      ],
      network: {
        path: ["orders-api", "payment-service", "Provider"],
        latency: ["12ms", "4.8s", "4.6s"],
        failures: "7.9% provider timeouts",
      },
      database: {
        active: 10,
        idle: 18,
        max: 30,
        waiting: 0,
        avg: "41ms",
        p95: "86ms",
        locks: 0,
        note: "Healthy; no pool pressure.",
      },
      deployment: [
        {
          version: "v3.9.2",
          time: "2 hours ago",
          status: "HEALTHY",
          changes: ["API client logging"],
        },
      ],
    },
    [
      {
        label: "Disable/extend provider retries",
        key: "disable_retries",
        correct: true,
      },
      { label: "Route to provider fallback", key: "fallback", correct: true },
      { label: "Rollback deployment", key: "rollback", correct: false },
      { label: "Increase DB pool", key: "increase_pool", correct: false },
    ],
    [
      "18:05",
      "Provider healthy",
      "18:08",
      "Provider latency rises",
      "18:09",
      "Retries begin",
      "18:11",
      "Checkout timeout alert",
    ],
  ),
  base(
    "INC-1330",
    "API Worker CPU Saturation",
    "SEV-2",
    "search-api",
    "MEDIUM",
    "cpu_saturation",
    {
      latency: 3.5,
      p50: 1.1,
      p95: 3.5,
      p99: 5.9,
      errorRate: 7.2,
      rps: 920,
      cpu: 97,
      memory: 58,
    },
    {
      metrics: {
        points: [42, 45, 51, 59, 68, 76, 85, 91, 97],
        note: "CPU climbs with request queue depth while memory and DB remain stable.",
      },
      logs: [
        ["13:14:01", "INFO", "search-api", "Traffic spike detected"],
        ["13:15:11", "WARN", "search-api", "Worker CPU 85%"],
        ["13:16:07", "WARN", "search-api", "Request queue growing"],
        [
          "13:17:19",
          "ERROR",
          "search-api",
          "Worker execution deadline exceeded",
        ],
      ],
      network: {
        path: ["Client", "Load Balancer", "search-api", "PostgreSQL"],
        latency: ["10ms", "7ms", "2.9s"],
        failures: "6.7% timeouts",
      },
      database: {
        active: 11,
        idle: 17,
        max: 30,
        waiting: 0,
        avg: "45ms",
        p95: "98ms",
        locks: 0,
        note: "Database is not saturated.",
      },
      deployment: [
        {
          version: "v7.0.3",
          time: "yesterday",
          status: "HEALTHY",
          changes: ["search tuning"],
        },
      ],
    },
    [
      { label: "Scale workers", key: "scale", correct: true },
      { label: "Reduce expensive query load", key: "load_shed", correct: true },
      { label: "Increase DB pool", key: "increase_pool", correct: false },
      { label: "Flush DNS/cache", key: "dns", correct: false },
    ],
    [
      "13:10",
      "Traffic baseline",
      "13:14",
      "Traffic spike",
      "13:15",
      "CPU > 85%",
      "13:16",
      "Queue grows",
      "13:17",
      "Latency alert",
    ],
  ),
];
export const explain = {
  db_connection_pool:
    "A connection pool caps concurrent database connections. When all connections are occupied, requests wait for a free connection and latency rises.",
  memory_leak:
    "A memory leak keeps objects reachable after they should be released. Heap usage can trend upward across garbage-collection cycles.",
  bad_deployment:
    "A release can introduce a regression. Correlating the first failures with deployment time helps separate a release problem from an infrastructure problem.",
  dns_failure:
    "DNS converts hostnames into routable addresses. Resolution failures can break an otherwise healthy network path.",
  external_dependency:
    "A slow dependency can dominate end-to-end latency even when the local service, database and network remain healthy.",
  cpu_saturation:
    "When CPU approaches capacity, work queues and scheduling delays increase. Latency can rise without a database problem.",
};
